### ISSUE TITLE
`link` command causes Unhandled rejection TypeError: this._bridge.getMyGitterUserId is not a function

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-gitter#3]
No idea why

    Admin: link !EhDVyqxqPCuiTloAkb:matrix.org neovim/neovim
    Unhandled rejection TypeError: this._bridge.getMyGitterUserId is not a function
        at BridgedRoom.joinAndStart._bridge.getMyGitterUserId.then._gitter.rooms.join.then [as joinAndStart] (/home/gitteras/matrix-appservice-gitter/lib/BridgedRoom.js:22:23)
        at /home/gitteras/matrix-appservice-gitter/index.js:158:30
        at tryCatcher (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:581:18)
        at Async._drainQueue (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:128:12)
        at Async._drainQueues (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by leonerd** [comment]
Fixed; link now works again
