### ISSUE TITLE
Latest `master` doesn't run in production

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-gitter#32]
Unsure quite why; failures look like:

```
Unhandled rejection TypeError: Cannot read property 'authedRequest' of undefined
    at PrometheusMetrics.MatrixClient.roomState (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/client.js:2068:22)
    at MatrixClient.matrixClientPrototype.(anonymous function) [as roomState] (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/lib/components/prometheusmetrics.js:275:25)
    at queryRoomState (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/lib/components/state-lookup.js:93:26)
    at /home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/lib/components/state-lookup.js:113:9
    at tryCatcher (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:71:37)
    at StateLookup.trackRoom (/home/gitteras/matrix-appservice-gitter/node_modules/matrix-appservice-bridge/lib/components/state-lookup.js:90:38)
    at /home/gitteras/matrix-appservice-gitter/lib/Main.js:655:36
    at tryCatcher (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/gitteras/matrix-appservice-gitter/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Did not work at 0df677c, rolled back to 6f5ee4b

**Comment by leonerd** [comment]
Ah oops. Appears to be a bug in `matrix-appservice-bridge`.

**Comment by leonerd** [comment]
Fixed.
